a = input('Digite algo')
print('O valor primitivo desse valor é', type(a))
print('É uma letra?', a.isalpha())
print('Está capitalizada?', a.istitle())
print('Possui espaço?', a.isspace())
print('É um número?', a.isnumeric())
print('É alpha numérico?', a.isalnum())
print('Está em maiúsculo?', a.isupper())
print('Está em minúsculo?', a.islower())
